global:
  # How frequently to scrape targets by default.
  scrape_interval:  10s
  # How long until a scrape request times out.
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'ticketbroker'
    static_configs:
    - targets: ['ticketbroker:80']