{
 "title": "TicketBroker",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sales funnel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(views[5m]))", "legendFormat": "views" },
    { "expr": "sum(rate(orders[5m]))", "legendFormat": "orders" },
    { "expr": "sum(rate(payments[5m]))", "legendFormat": "payments" }
   ]
  },
  {
   "title": "Orders by ticketType/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(orders[30s])) by (ticketType)",
     "legendFormat": "{{ ticketType }} "
    }
   ]
  },
  {
   "title": "Orders by paymentType/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(orders[30s])) by (paymentType)",
     "legendFormat": "{{ paymentType }}"
    }
   ]
  },
  {
   "title": "Payments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(payments[1m])", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Views / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(views[30s])", "legendFormat": "views" }
   ]
  }
 ]
}