{
 "title": "TechnicalDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "5xx / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"ticketbroker\", controller!=\"\", code=~\"5..\"}[1m])) by (action, controller)",
     "legendFormat": "{{ controller }}/{{ action }}"
    }
   ]
  },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(http_requests_received_total{job=\"ticketbroker\", controller!=\"\"}[1m])) * 60",
     "legendFormat": "{{ controller }}/{{ action }} - {{code}}"
    }
   ]
  },
  {
   "title": "Duration 95%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller!=\"\"}[1m])) by (controller, action, le))",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job=\"ticketbroker\"}",
     "legendFormat": "Threads - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"ticketbroker\"}",
     "legendFormat": "Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{job=\"ticketbroker\"}[2m]))",
     "legendFormat": "CPU - {{ instance }}"
    }
   ]
  }
 ]
}